Port ${AIBOX_PORT}
Listen 127.0.0.1

Timeout 600

ConnectPort 443
LogLevel Connect

LogFile "${AIBOX_DIR}/tinyproxy.log"
PidFile "${AIBOX_DIR}/tinyproxy.pid"

# Filter "${AIBOX_DIR}/tinyproxy.whitelist"
# FilterType ere
# FilterDefaultDeny Yes

MaxClients 20

Allow 127.0.0.1
